### ISSUE TITLE
Can't create menu in single store mode

### ISSUE THREAD

**Issue by vseager** [SnowdogApps/magento2-menu#226]
If Magento's "Single Store Mode" is enabled, you cannot create a new menu in the admin:

```
[2021-12-13 21:05:05] main.CRITICAL: TypeError: Argument 1 passed to Snowdog\Menu\Model\Menu\Interceptor::saveStores() must be of the type array, null given, called in /vendor/snowdog/module-menu/Controller/Adminhtml/Menu/Save.php on line 64 and defined in /generated/code/Snowdog/Menu/Model/Menu/Interceptor.php:38
Stack trace:
#0 /vendor/snowdog/module-menu/Controller/Adminhtml/Menu/Save.php(64): Snowdog\Menu\Model\Menu\Interceptor->saveStores(NULL)
#1 /vendor/magento/framework/Interception/Interceptor.php(58): Snowdog\Menu\Controller\Adminhtml\Menu\Save->execute()
#2 /vendor/magento/framework/Interception/Interceptor.php(138): Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor->___callParent('execute', Array)
#3 /vendor/magento/framework/Interception/Interceptor.php(153): Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor->Magento\Framework\Interception\{closure}()
#4 /generated/code/Snowdog/Menu/Controller/Adminhtml/Menu/Save/Interceptor.php(23): Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor->___callPlugins('execute', Array, Array)
#5 /vendor/magento/framework/App/Action/Action.php(111): Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor->execute()
#6 /vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /vendor/magento/framework/Interception/Interceptor.php(138): Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor->___callParent('dispatch', Array)
#9 /vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#10 /vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 /vendor/magento/framework/Interception/Interceptor.php(153): Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /generated/code/Snowdog/Menu/Controller/Adminhtml/Menu/Save/Interceptor.php(32): Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#13 /vendor/magento/framework/App/FrontController.php(245): Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor), Object(Magento\Framework\App\Request\Http))
#15 /vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Snowdog\Menu\Controller\Adminhtml\Menu\Save\Interceptor))
#16 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#18 [internal function]: Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /vendor/m2epro/magento2-extension/Plugin/AbstractPlugin.php(36): call_user_func_array(Object(Closure), Array)
#20 /vendor/m2epro/magento2-extension/Plugin/HealthStatus/Magento/Framework/App/FrontController.php(45): Ess\M2ePro\Plugin\AbstractPlugin->execute('dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Array)
#21 /vendor/magento/framework/Interception/Interceptor.php(135): Ess\M2ePro\Plugin\HealthStatus\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#24 /vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#26 /vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#27 /pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
```

**Comment by andrzejborkowski** [comment]
I can't replicate the issue on m2.4.2 and menu module 2.18.0 with single store mode enabled. Could you please provide more details about how to replicate the issue?

**Comment by andrzejborkowski** [comment]
I created an internal ticket DEV-86709 to check the issue deeper based on the provided information, however, I still can't replicate the issue

**Comment by goranhorvathr** [comment]
Hey guys. The issue is there. We just encountered it with latest Snowdog menu on 2.4.3.p1 in production mode. I will investigate what actually happens too as we are making snowdog compat module for hyva.

**Comment by tobiasolge** [comment]
same issue here.

**Comment by andrzejborkowski** [comment]
the fix is already in develop branch and we will release the module soon
