### ISSUE TITLE
magento2 customer admin grid not loaded properly in Magento2.4.3p1

### ISSUE THREAD

**Issue by Pekkonen** [SnowdogApps/magento2-menu#240]
I have a problem with Magento customer admin grid not loaded properly in Magento2.4.3p1. First row only loaded.
![Customers-Customers-Magento-Admin](https://user-images.githubusercontent.com/31384473/157088228-efe874d2-19b6-45b0-9639-88bf4d2d5fc2.jpg)
And I have error in console:
```
knockout.js:3753 Uncaught TypeError: Unable to process binding "text: function(){return $col.getLabel($row()) }"
Message: Cannot read properties of undefined (reading 'isValid')
    at UiClass.getLabel (/static/version1646674321/adminhtml/Magento/backend/en_US/Magento_Ui/js/grid/columns/date.js:55:25)
    at UiClass.getLabel (/static/version1646674321/adminhtml/Magento/backend/en_US/mage/utils/wrapper.js:109:34)
    at text (eval at createBindingsStringEvaluator (/static/version1646674321/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:3221:28), <anonymous>:3:69)
    at update (/static/version1646674321/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:5157:54)
    at ko.dependentObservable.disposeWhenNodeIsRemoved (/static/version1646674321/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:3745:45)
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (/static/version1646674321/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:2331:115)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (/static/version1646674321/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:2288:41)
    at Function.evaluateImmediate (/static/version1646674321/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:2253:40)
    at Object.ko.computed.ko.dependentObservable (/static/version1646674321/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:2085:40)
    at /static/version1646674321/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:3743:40
```
When I disable a module  - bin/magento module:enable Snowdog_Menu
I see correct grid.
Do you know about this problem?

**Comment by Pekkonen** [comment]
@andrzejborkowski 
I've checked on another instance of Magento with fresh installation and for now everything looks like fine!
I think problem was inside my old instance of Magento 2.4.3-p1

**Comment by andrzejborkowski** [comment]
thanks for update, closing the issue then
